version: "3"

services:
  zookeeper:
    image: zookeeper:3.5
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/data

  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 # We will only une one broker here
#      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cassandra:
    image: cassandra:3.11
    ports:
      - "7000:7000"
    volumes:
      - cassandra-data:/var/lib/cassandra

  carriers:
    image: experiments/carriers:latest
    ports:
      - "9001:9000"
    depends_on:
      - kafka
      - cassandra
    environment:
      - CASSANDRA_HOSTS=[cassandra]

  organizations:
    image: experiments/organizations:latest
    ports:
      - "9000:9000"
    depends_on:
      - kafka
      - cassandra
      - carriers
    environment:
      - CASSANDRA_HOSTS=[cassandra]

volumes:
  cassandra-data:
  zookeeper-data:
